# Generated by Django 3.0 on 2021-02-25 20:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('manufacturing_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('tracking_code', models.CharField(max_length=250)),
                ('producer', models.CharField(max_length=250)),
                ('notice', tinymce.models.HTMLField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
